name: gs_init_compare
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch::pytorch=2.4
  - pytorch::torchvision
  - pytorch::pytorch-cuda=12.1
  - pillow=10.4.0
  - tyro=0.8.11
  - ipykernel=6.29.5
  - numpy<2.0
  - matplotlib=3.9.2
  - plyfile=1.1
  - timm=1.0.9
  - tensorboard
  - tensorboardx=2.6.2.2
  - imgaug=0.4.0
  - iopath=0.1.10
  - fire=0.7.0
  - gradio=4.44.1
  - plotly=5.24.1
  - trimesh=4.4.9
  - exifread=3.0.0
  - opencv=4.10.0
  - torchmetrics
  - scikit-learn
  - tensorly

