[tool.poetry]
name = "gs-initialization-comparison"
version = "0.1.0"
description = ""
authors = ["Ivan Desiatov <desiaiva@fit.cvut.cz>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.10"
torch = { version = "^2.4.0+cu121", source = "pytorch_source" }
torchvision = { version = "^0.19.1+cu121", source = "pytorch_source" }
gsplat = { version = "^1.4.0+pt24cu121", source = "gsplat_source" }
pillow = "^10.4.0"
tyro = "^0.8.11"
ipykernel = "^6.29.5"
mmcv = "^2.2.0"
numpy = "^2.1.2"
xformers = {version = "^0.0.28.post1", source = "pytorch_source"}
datetime = "^5.5"
matplotlib = "^3.9.2"
plyfile = "^1.1"
html4vision = "^0.4.3"
timm = "^1.0.9"
tensorboardx = "^2.6.2.2"
imgaug = "^0.4.0"
iopath = "^0.1.10"
imagecorruptions = "^1.1.2"
opencv-python = "^4.10.0.84"
fire = "^0.7.0"
gradio = "^4.44.1"
gradio-imageslider = "^0.0.20"
cupy-cuda12x = "^13.3.0"
plotly = "^5.24.1"
trimesh = "^4.4.9"
exifread = "^3.0.0"
nerfview = "^0.0.3"
torchmetrics = "^1.4.2"
pycolmap = {git = "https://github.com/rmbrualla/pycolmap", rev = "cc7ea4b7301720ac29287dbe450952511b32125e"}

[[tool.poetry.source]]
name = "pypi"
priority = "primary"

[[tool.poetry.source]]
name = "pytorch_source"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[[tool.poetry.source]]
name = "gsplat_source"
url = "https://docs.gsplat.studio/whl/pt24cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
